### PR TITLE
Microverse Project Design & UX: Smashing Magazine

### PR DESCRIPTION
**Pull request by Janluc**
## Smashing Magazine
- Used design principles to apply heatmap of website
- Use of Flexbox and Grid for positioning of elements
- Heatmap color difference according to visual hierarchy

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning::vertical_traffic_light: 

### Hello @Janluc & @jcy2704 :wave: 

**I must say, you guys have done an awesome job right here :clap:**
- Your linters are green :green_circle: 
- Proper use of CSS grid / position :100: 
- Use of semantic tags :ok_hand: 
- Good understanding of the project :heavy_check_mark: 

**In summary, this project is almost complete. Talking about completion, there are some issues we need to fix before this project can be approved. Let's get to it:**

**[ REQUIRED CHANGES ]**

- [ ] I believe you built your layout using a width of 1440px on the original page (through developer tools). However, when your project is viewed on that same size, your page seems to have a horizontal scroll bar. Kindly check which of your containers is causing this behavior and fix it. 

- [ ] It is a requirement that all your articles should use `<article>` tag. 
- You used the `<div>` tag for most of your articles; the only articles you built with the `<article>` tag is the first four(4) articles in the 2-articles-per-rows section. Please use the `<article>` tag for **all other articles** too. 



- [ ] In the footer section, although the content  is not important, the items must be linked. Please link your footer items using the `<a>` tag.




**Kindly make the required changes and request for another review when you are done.**

*__You can reach out to me on slack (@taofeekolalere) or GitHub (@teekaytech).__*

**Happy coding. :man_technologist:**

**Review by jubaan — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle:

## :wave: :wave: Hello!! Great effort in the project :clap :clap:!!

## Required Changes
### [Mandatory] :red_circle: 

- [ ] these elements should all be links, the content is not important.
image

- [ ] Update the live preview link in the README. This should fix the issues above.

### [Comments] :green_circle: 

- The README besides the project is one of the most important files in the repository. It is important to update it as the project changes.

- [ ] Project has horizontal scrolling. This is an issue that is caused by screen size where the project is seen, while is out of the scope of the goals of the project, it is important to mention it as it will be a problem for future exercises. To solve this, make a habit of using the browser media query inspector and check if the project maintain proportions over different screen sizes. Keep in mind that all users will not have always the same screen size as the programmer.

## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

**Comment by jcy2704** [comment]
@jubaan Hello, thanks for the code review. However, from the changes you've suggested, the footer, were already links, we just added the bulletpoint to make it look like the original site, but all of it are links.

**Comment by jubaan** [comment]
> @jubaan Hello, thanks for the code review. However, from the changes you've suggested, the footer, were already links, we just added the bulletpoint to make it look like the original site, but all of it are links.

:wave: Hello @jcy2704, I noticed, if you check the issue after that is about updating the README, and doing that fixing the issues before ;).

**Comment by jcy2704** [comment]
> 👋 Hello @jcy2704, I noticed, if you check the issue after that is about updating the README, and doing that fixing the issues before ;).

Do I need to request a new pull request even if you are review right now?

**Review by jubaan — APPROVED** [review]
# Status: Approved :tada: :tada: :tada:

## Great job Team!! :clap: :clap:

You've worked on all required changes! You may now merge to master.

## See you at the top :rocket:!!

**Pull request merged**
